### ISSUE TITLE
add 3 letter code 

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/clanstats#1]
hey this looks good except two things as we discussed:
a) uncollapsing the counts so you get
MAN
MAN
MAN
instead of 
MAN 3

b) adding in the 3-letter code column from the original file

**Comment by andreiamatuni** [comment]
the latest commit fixes this. the batch_out_really_long folder has the 6/7 month reports in this form, and there's also a single file containing the aggregate long output now (rather than a single file per subject/visit), it's called aggregate_long.csv (in the main folder)

**Comment by ebergelson** [comment]
great--can you just point me to the directions or the readme where it says
how to create these files from whatever's in the data folder? [after we do
the needed cleanup we can just add the missing files into the data folder,
and run the relevant script, right?]

**Comment by andreiamatuni** [comment]
I just added a readme. You can view it on the clanstats repo's main page [here](https://github.com/SeedlingsBabylab/clanstats). Adding .cex files to the data directory and running the scripts will work. I'll add parse_clan2's .cha parser to clanstats.py so it can handle the new format files too.
